<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_test</name>
   <tag></tag>
   <elementGuidId>31437edc-18d6-44b0-bb0b-a5f0fa6df0f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//b[@id = '${b_id}' and @class = 'chzn-single']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;${id}_chzn&quot;]/a/div/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>${b_id}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chzn-single</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
   </webElementProperties>
</WebElementEntity>
