<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul</name>
   <tag></tag>
   <elementGuidId>454180b9-09e7-4acc-b94e-93f0ed2cb390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'chzn-results' and @id = '${id_test}']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;${id1}_chzn_o_5&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chzn-results</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>${id_test}</value>
   </webElementProperties>
</WebElementEntity>
