<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b</name>
   <tag></tag>
   <elementGuidId>f35066e1-3a1e-4b4b-91b7-b28891fa2ee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selVC8_chzn > a.chzn-single > div > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='selVC8_chzn']/a/div/b</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;selVC8_chzn&quot;)/a[@class=&quot;chzn-single&quot;]/div[1]/b[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selVC8_chzn&quot;)/a[@class=&quot;chzn-single&quot;]/div[1]/b[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selVC8_chzn']/a/div/b</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/div/span/div/a/div/b</value>
   </webElementXpaths>
</WebElementEntity>
