<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email</name>
   <tag></tag>
   <elementGuidId>41d6a015-2b91-4c2a-a788-82e0201c8298</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Leads_editView_fieldName_email&quot;)[count(. | //input[@id = 'Leads_editView_fieldName_email' and @class = 'input-large' and @data-validation-engine = 'validate[funcCall[Vtiger_Base_Validator_Js.invokeValidation]]' and @name = 'email' and @data-fieldinfo = '{&quot;mandatory&quot;:false,&quot;presence&quot;:true,&quot;quickcreate&quot;:true,&quot;masseditable&quot;:false,&quot;defaultvalue&quot;:false,&quot;type&quot;:&quot;email&quot;,&quot;name&quot;:&quot;email&quot;,&quot;label&quot;:&quot;Email&quot;}']) = count(//input[@id = 'Leads_editView_fieldName_email' and @class = 'input-large' and @data-validation-engine = 'validate[funcCall[Vtiger_Base_Validator_Js.invokeValidation]]' and @name = 'email' and @data-fieldinfo = '{&quot;mandatory&quot;:false,&quot;presence&quot;:true,&quot;quickcreate&quot;:true,&quot;masseditable&quot;:false,&quot;defaultvalue&quot;:false,&quot;type&quot;:&quot;email&quot;,&quot;name&quot;:&quot;email&quot;,&quot;label&quot;:&quot;Email&quot;}'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Leads_editView_fieldName_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Leads_editView_fieldName_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Leads_editView_fieldName_email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-large</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-engine</name>
      <type>Main</type>
      <value>validate[funcCall[Vtiger_Base_Validator_Js.invokeValidation]]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fieldinfo</name>
      <type>Main</type>
      <value>{&quot;mandatory&quot;:false,&quot;presence&quot;:true,&quot;quickcreate&quot;:true,&quot;masseditable&quot;:false,&quot;defaultvalue&quot;:false,&quot;type&quot;:&quot;email&quot;,&quot;name&quot;:&quot;email&quot;,&quot;label&quot;:&quot;Email&quot;}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Leads_editView_fieldName_email&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Leads_editView_fieldName_email']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='Leads_detailView_fieldValue_email']/span[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/span[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
